name: MachineLearning

channels:
  - defaults
  - conda-forge

dependencies:
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - jupyter
  - nltk
  - statsmodels
  - plotly
  - requests
  - beautifulsoup4
  - tensorflow
  - keras
  - pytorch
  - torchvision
  - python=3.10.0