name: Pytorch

channels:
  - defaults
  - conda-forge
  
dependencies:
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - jupyter
  - nltk
  - statsmodels
  - plotly
  - requests
  - beautifulsoup4
